"""Global counseling doctrine — Tier-1 knowledge every AI counselor answer is
grounded on (trap handling, scholarship rules, process knowledge). Tenant CKP
prose is chunked into the same store with scope='tenant'."""

CORPUS = [
    dict(title="Placement conversation doctrine", scope="global", section="no guarantees",
         content="Never promise a job, a salary, or placement percentage beyond the college's approved statistics. Correct framing: placements depend on student effort and market conditions; share only approved year-wise stats (placed % of eligible students, offers, top/average package) with the year attributed. If asked for a guarantee, explain honestly that no genuine college can guarantee jobs, and that the college's record is the best evidence. Suggest a campus visit to meet the placement officer."),
    dict(title="JVD fee reimbursement guidance (AP)", scope="global", section="scholarship basics",
         content="Jagananna Vidya Deevena (JVD) is Andhra Pradesh's fee reimbursement scheme for eligible convener-quota students. Indicative criteria: AP domicile, admission through convener quota via counselling, family income within the government-notified ceiling (approximately Rs 2.5 lakh per year, subject to change), and valid caste/income certificates as per current government rules. Rules and ceilings change year to year: ALWAYS add that the college office will verify current-year eligibility with official documents before confirming. Never confirm reimbursement eligibility in chat."),
    dict(title="EAPCET counselling process", scope="global", section="web options",
         content="AP EAPCET admissions happen through centralized counselling: certificate verification, then web options entry where students list college-and-branch choices using college codes and branch codes, then seat allotment and fee payment at a helpline centre. Tier-3 colleges should be listed early in web options for realistic ranks. Management-quota (non-convener) seats are booked directly at the college in parallel and do not require EAPCET rank, though eligibility rules (intermediate marks, subject requirements) still apply."),
    dict(title="Admission document checklist", scope="global", section="documents",
         content="Standard admission checklist: EAPCET hall ticket and rank card (if applicable), SSC memo, Intermediate memo and marks, transfer certificate, study certificates (6th to 12th), caste and income certificates (for reimbursement eligibility), Aadhaar, ration card copy, photos, and for management quota the booking token receipt. Originals plus 2-3 photocopy sets."),
    dict(title="Management quota booking doctrine", scope="global", section="process",
         content="Management-quota admission flow: enquiry -> campus visit -> branch seat availability check -> booking token with receipt (amount varies by college) -> document submission -> fee payment as per schedule. Refund rules for cancelled bookings are institutional and governed by the fee regulation norms: refund questions MUST be handed to the college office, never answered from memory."),
    dict(title="Hostel conversation doctrine", scope="global", section="trust",
         content="Parents' top hostel concerns: safety, food quality, study environment, wardens, and cost. Best practice: share the approved fee and facilities, offer recent photos, and invite them to visit the hostel and mess unannounced — a confident college welcomes surprise visits. Never overstate facilities; describe what is in the approved knowledge pack only."),
    dict(title="Follow-up speed doctrine", scope="global", section="conversion",
         content="Speed-to-lead decides conversions in admissions: contacting an enquiry within 5 minutes vs 30 minutes changes conversion odds by roughly 10x. Every lead should get an instant acknowledgment, a counselor call the same day, and structured follow-ups: day-1 nudge, day-3 campus-visit invite, day-7 deadline reminder. Track cost-per-joined-student per source and shift budget to the cheapest sources."),
    dict(title="DPDP consent script", scope="global", section="consent",
         content="Before storing or using a parent's contact details for follow-up, take explicit consent (Digital Personal Data Protection Act, 2023). Script: 'May I share your name and number with our admission counselor so they can call you? (Yes/No)'. Store the consent timestamp. If the student appears to be under 18, consent must be demonstrably from the parent/guardian. Honor stop requests immediately and log them."),
    dict(title="Trap-question escape doctrine", scope="global", section="safety",
         content="Five trap classes the AI must never answer with invented facts: (1) job/placement guarantees, (2) exact salary promises, (3) certain scholarship approvals, (4) refund policy rulings, (5) rank/cutoff predictions for future years. Response pattern: acknowledge honestly, share only approved data with year attribution, and offer the human path (counselor call or office visit). Honesty converts better than overpromising and protects the college legally (Consumer Protection Act 2019)."),
    dict(title="Tier-3 parent objections playbook", scope="global", section="objections",
         content="Common objections and honest responses: 'Why your college and not the one near my town?' -> talk branch strengths, placement evidence, hostel/transport fit, fee value. 'Fees are high' -> explain convener-quota route and JVD guidance, management-quota token flexibility is office's domain. 'Placements are weak in tier-3' -> share approved stats honestly plus training/internship support, invite to meet placed alumni. 'Will I get CSE?' -> explain last year's closing ranges and realistic branch options; never promise a seat."),
]
